#!/usr/bin/env bash
# This script installs nginx and configures it to meet the specified requirements

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get -y install nginx

# Allow Nginx through the firewall
sudo ufw allow "Nginx HTTP"

# Create a simple HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart nginx using the reload command
service nginx restart
